### ISSUE TITLE
Exception reported: Invalid address 0xb09f is pointing to reserved memory

### ISSUE THREAD

**Issue by Z-RAY-Z** [GAMMACASE/MomSurfFix#4] opened 2020-08-27 19:51 UTC
Иногда мелькает в логах:
L 08/25/2020 - 19:12:31: [SM] Exception reported: Invalid address 0xb09f is pointing to reserved memory.
L 08/25/2020 - 19:12:31: [SM] Blaming: momsurffix2.smx
L 08/25/2020 - 19:12:31: [SM] Call stack trace:
L 08/25/2020 - 19:12:31: [SM]   [0] LoadFromAddress
L 08/25/2020 - 19:12:31: [SM]   [1] Line 154, momsurffix/gametrace.sp::CGameTrace.startsolid.get
L 08/25/2020 - 19:12:31: [SM]   [2] Line 472, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\momsurffix2.sp::TryPlayerMove
L 08/25/2020 - 19:12:31: [SM]   [3] Line 259, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\momsurffix2.sp::TryPlayerMove_Dhook

Версия игры:
Protocol version 13765 [1177/1177]
Exe version 1.37.6.5 (csgo)
Exe build: 20:50:28 Aug 17 2020 (7929) (730)
Плагины:
SourceMod (1.10.0.6492) by AlliedModders LLC & Metamod:Source 1.11.0-dev+1128
Momentum surf fix '2" (1.1.3) by GAMMA CASE

**Comment by GAMMACASE** [comment] 2020-08-27 20:10
Please keep this in english. Also knowing some ways to reproduce it would be useful, or else it's hard to track down.

**Comment by GAMMACASE** [comment] 2022-03-25 20:59
Closing due to insufficient amount of information provided. Please, reopen once you are ready to communicate.

**Closed as completed by GAMMACASE** 2022-03-25 20:59 UTC
Labels: bug, question
