### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Uronic** [GAMMACASE/MomSurfFix#10] opened 2022-01-12 11:11 UTC
`L 01/12/2022 - 06:42:37: [SM] Exception reported: [momsurffix2] Can't get "sm_pSingleton" address from gamedata.
L 01/12/2022 - 06:42:37: [SM] Blaming: momsurffix2.smx
L 01/12/2022 - 06:42:37: [SM] Call stack trace:
L 01/12/2022 - 06:42:37: [SM]   [0] SetFailState
L 01/12/2022 - 06:42:37: [SM]   [1] Line 660, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\momsurffix2.sp::SetFailStateCustom
L 01/12/2022 - 06:42:37: [SM]   [2] Line 149, momsurffix/gamemovement.sp::InitGameMovement
L 01/12/2022 - 06:42:37: [SM]   [3] Line 99, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\momsurffix2.sp::OnPluginStart
L 01/12/2022 - 06:42:37: [SM] Unable to load plugin "momsurffix2.smx": Error detected in plugin startup (see error logs)`

As far as I can tell, no issues in-game. (CSGO)

**Comment by GAMMACASE** [comment] 2022-01-12 11:57
> As far as I can tell, no issues in-game. (CSGO)

Cuz the plugin failed to load.

What OS version are you on and what version of the plugin are you running? I'd recommend you to update the gamedata and plugin (if it wasn't the latest one already) to the latest one and recheck if it still fails to load.

**Comment by Uronic** [comment] 2022-01-12 12:41
> > As far as I can tell, no issues in-game. (CSGO)
> 
> Cuz the plugin failed to load.
> 
> What OS version are you on and what version of the plugin are you running? I'd recommend you to update the gamedata and plugin (if it wasn't the latest one already) to the latest one and recheck if it still fails to load.

The plugin does load. It is just that I have to load it myself with sm plugins load. The error only appears on server startup. I checked to see if I have the latest gamedata and I do.

**Comment by GAMMACASE** [comment] 2022-01-12 12:48
You still have not answered all of my questions

**Comment by Uronic** [comment] 2022-01-12 12:49
> You still have not answered all of my questions

Oh sorry, I am on Windows. The first time I tried typing a reply I wanted to go and check if I had the gamedata installed and when I went back to actually reply I forgot to re-type what OS I am on, my bad.

**Comment by GAMMACASE** [comment] 2022-01-12 12:57
And what version of the plugin? Cuz I'm unable to reproduce your issue on my windows machine.

**Comment by GAMMACASE** [comment] 2022-01-12 12:59
You also said that you can load the plugin just fine manually, is it also shown as loaded when you type ``sm plugins list`` in server console?

**Comment by Uronic** [comment] 2022-01-12 13:00
> You also said that you can load the plugin just fine manually, is it also shown as loaded when you type `sm plugins list` in server console?

Yes I was actually just pulling up the plugin version through sm plugins list as well. It is "Momentum Surf fix '2'" (1.1.3)

**Comment by GAMMACASE** [comment] 2022-01-12 13:03
The line numbers in your error log doesn't match with the master branch tho, could you please update to the master branch anyway and see if it fixes your issue?

**Comment by Uronic** [comment] 2022-01-12 13:08
> The line numbers in your error log doesn't match with the master branch tho, could you please update to the master branch anyway and see if it fixes your issue?

Oh yeah you're right, the master branch is 1.1.4. I updated but issue is still not fixed. I mean it doesn't affect me I guess the plugin loads and works anyways

**Comment by GAMMACASE** [comment] 2022-01-12 13:11
The thing is that I'm unable to reproduce your issue to fix it, and that's anyway looks way too strange to be an issue on a first load only. Would you be able to remove all other plugins/extensions and test with only momsurffix2 alone?

**Comment by Uronic** [comment] 2022-01-12 13:20
> The thing is that I'm unable to reproduce your issue to fix it, and that's anyway looks way too strange to be an issue on a first load only. Would you be able to remove all other plugins/extensions and test with only momsurffix2 alone?

It is probably a plugin conflict somewhere but my server is one with a lot of plugins, some unloaded and loaded at certain times (multimod). It would take a lot of time and would be pointless because the plugin conflict is clearly something no one else has except me. I will just accept the fact the error will appear on startup.

**Comment by GAMMACASE** [comment] 2022-01-12 13:28
Even under extensive loading\unloading I'm unable to reproduce your case. Will close this issue until more reproduction steps or info is available.

**Closed as completed by GAMMACASE** 2022-01-12 13:28 UTC
Labels: bug, question
